[package]
    name = "cordy"
    version = "0.1.0"
    edition = "2021"

[dependencies]
    cordy-sys = { path = "../cordy-sys" }
    rustyline = "12.0.0"
    mimalloc = { version = "0.1.37", default-features = false }
